### ISSUE TITLE
Suggestion - reenable join in testMultipleProducersAndConsumersInArray

### ISSUE THREAD

**Issue by bensbox** [zerustech/pthreads-tutorial#2]
Hi Michael,

i like to suggest to reenable the join() calls in the BasicProducerConsumerTest::testMultipleProducersAndConsumersInArray test. Even though your code is running just fine in the correct order (the notification at the end finishes last), the join() at the end is the better usage.

To clarify i adapted your code from [#602 (krakjoe/pthreads)](https://github.com/krakjoe/pthreads/issues/602) and added the following line at the end:
```php
echo "==== All producers reported their inventory ===";
```

In relation to your test i would expect, that the asterisk appears before my output, but instead it appears after it, because the main thread is not waiting for the producers and is faster.
Additionally i doubt that krakjoe changed this behaviour completely, even though your example works currently.
> That's expected ...
> 
> The thread is destroyed implicitly, too early by the destruction of the array ... you should join all threads > you create.
I guess thats why he added the Pool object in v3 (besides making sure to avoid the implicit destruction).

Just saying, that somebody might have problems with it, when following your tutorial and adapting the array usage.

Thanks and keep up the good work!

**Comment by zerustech** [comment]
@bensbox Sorry for the late reply, but I have been quite busy recently. I have re-enabled the join operation in that script.
